language: java

jdk:
  - oraclejdk8
  
before_install:
  - chmod a+x gradlew

script: 
  - ./gradlew test --info
  - ./gradlew codeCoverageReport
  
after_success:
  - bash <(curl -s https://codecov.io/bash)