language: java

dist: trusty

jdk:
  - oraclejdk8
  
before_install:
  - chmod a+x gradlew

script: 
  - ./gradlew test
  
after_success:
  - ./gradlew jacocoRootReport coveralls
  - bash <(curl -s https://codecov.io/bash)